name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  actions: read
  checks: write
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - id: setup
      name: setup
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pip install numpy pytest pytest-timeout flake8
          pep8-naming flake8-docstrings
        max-score: null
        setup-command: python3 -m venv venv
        test-name: setup
        timeout: 1
    - id: package-install
      name: package-install
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pip install -e .
        max-score: 1
        setup-command: ''
        test-name: package-install
        timeout: 1
    - id: exercise-5-4
      name: exercise-5-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pytest tests/test_exercise_5_4.py
        max-score: 1
        setup-command: ''
        test-name: exercise-5-4
        timeout: 1
    - id: exercise-5-5
      name: exercise-5-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pytest tests/test_exercise_5_5.py
        max-score: 1
        setup-command: ''
        test-name: exercise-5-5
        timeout: 1
    - id: exercise-5-6
      name: exercise-5-6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m pytest tests/test_exercise_5_6.py
        max-score: 1
        setup-command: ''
        test-name: exercise-5-6
        timeout: 1
    - id: flake8-test
      name: flake8-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        command: venv/bin/python -m flake8 adt_examples/
        max-score: 1
        setup-command: ''
        test-name: flake8-test
        timeout: 1
    - env:
        EXERCISE-5-4_RESULTS: ${{steps.exercise-5-4.outputs.result}}
        EXERCISE-5-5_RESULTS: ${{steps.exercise-5-5.outputs.result}}
        EXERCISE-5-6_RESULTS: ${{steps.exercise-5-6.outputs.result}}
        FLAKE8-TEST_RESULTS: ${{steps.flake8-test.outputs.result}}
        PACKAGE-INSTALL_RESULTS: ${{steps.package-install.outputs.result}}
        SETUP_RESULTS: ${{steps.setup.outputs.result}}
      name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      with:
        runners: setup, package-install, exercise-5-4, exercise-5-5, exercise-5-6,
          flake8-test
